### ISSUE TITLE
Receiving Assert failed: (map? alias-table) 

### ISSUE THREAD

**Issue by arichiardi** [bensu/doo#113]
Hello Bensu, the last `0.1.7-SNAPSHOT` gives me a weird error:

I checked the code and I don't see what went wrong. Maybe `lein` (I am using `2.6.1`) changed the way they pass the `:alias` key? Btw I don't have any `:alias` key in my `project.clj`...

The error:

```
$ scripts/lein test-phantom
Exception in thread "main" java.lang.AssertionError: Assert failed: (map? alias-table)
	at doo.core$resolve_alias.invokeStatic(core.clj:23)
	at doo.core$resolve_alias.invoke(core.clj:23)
	at leiningen.doo$cli__GT_js_envs.invokeStatic(doo.clj:130)
	at leiningen.doo$cli__GT_js_envs.invoke(doo.clj:115)
	at leiningen.doo$doo.invokeStatic(doo.clj:201)
	at leiningen.doo$doo.doInvoke(doo.clj:193)
	at clojure.lang.RestFn.invoke(RestFn.java:460)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$partial_task$fn__5829.doInvoke(main.clj:272)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:322)
	at leiningen.core.main$apply_task.invoke(main.clj:308)
	at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:328)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:324)
	at leiningen.core.main$_main$fn__5895.invoke(main.clj:401)
	at leiningen.core.main$_main.invokeStatic(main.clj:394)
	at leiningen.core.main$_main.doInvoke(main.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.main$main_opt.invokeStatic(main.clj:314)
	at clojure.main$main_opt.invoke(main.clj:310)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

**Comment by arichiardi** [comment]
I saw that I receive unsurprisingly `nil` so that means that `(map? alias-table)` is too restrictive. I am going to open a PR with the fix

**Comment by bensu** [comment]
Thanks @arichiardi for the quick report/fix!

I fixed this problem at the plugin layer. I rather maintain a strict contract for the library and manage coercions close to the user.

**Comment by arichiardi** [comment]
Ok great, is it on the new SNAPSHOT already (just asking, no pressure :smile:) ?

**Comment by bensu** [comment]
It is.
