### ISSUE TITLE
Printing test failures with records currently broken

### ISSUE THREAD

**Issue by Deraen** [bensu/doo#180]
https://github.com/honzabrecka/karma-reporter/pull/18

Printing test failures with Records is currently broken, fipp 0.6.10 has fix for this:

```
LOG: 'ERROR: Exception outside tests:'
LOG: 'ERROR: #object[Error Error: Assert failed: (symbol? tag)]'
LOG: ''
LOG: 'ERROR: Stacktrace:'
LOG: 'ERROR: Error: Assert failed: (symbol? tag)
    at cljs$core$tagged_literal (http://localhost:9876/base/target/out/cljs/core.js:36975:8)
    at fipp$ednize$record__GT_tagged (http://localhost:9876/base/target/out/fipp/ednize.js:141:33)
    at fipp.edn.EdnPrinter.fipp$visit$IVisitor$visit_record$arity$2 (http://localhost:9876/base/target/out/fipp/edn.js:145:75)
    at fipp$visit$visit_record (http://localhost:9876/base/target/out/fipp/visit.js:316:14)
    at fipp$visit$visit_STAR_ (http://localhost:9876/base/target/out/fipp/visit.js:371:32)
    at fipp$visit$visit (http://localhost:9876/base/target/out/fipp/visit.js:412:31)
    at Function.fipp.edn.pprint.cljs$core$IFn$_invoke$arity$2 (http://localhost:9876/base/target/out/fipp/edn.js:412:67)
    at fipp$edn$pprint (http://localhost:9876/base/target/out/fipp/edn.js:393:24)
    at Function.fipp.clojure.pprint.cljs$core$IFn$_invoke$arity$2 (http://localhost:9876/base/target/out/fipp/clojure.js:526:24)
    at fipp$clojure$pprint (http://localhost:9876/base/target/out/fipp/clojure.js:512:28)'
LOG: 'WARNING: doo's exit function was not properly set'
LOG: '#object[TypeError TypeError: Cannot read property 'call' of null]'
HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 16 of 17 SUCCESS (0 secs / 0.163 secs)
```

**Comment by bensu** [comment]
Should we update to the latest karma-reporter once that is out? Can you please ping us when it is?

**Comment by Deraen** [comment]
@bensu @miikka Karma-reporter 3.1.0 is now available https://clojars.org/karma-reporter
