### ISSUE TITLE
There is no planck support, despite the README stating it

### ISSUE THREAD

**Issue by simongray** [bensu/doo#187]
Support for Planck is advertised in the readme and in the docstrings of the source code, but attempting to use Planck results in this assertion error:

```
$ lein doo planck test once
Exception in thread "main" java.lang.AssertionError: Assert failed: The given alias: :planck didn't resolve to any runners. Try any of: karma-slimer, opera, safari, firefox-headless, phantom, chrome-headless, node, firefox, slimer, electron, chrome, rhino, ie, karma-phantom, chrome-canary, nashorn, headless, default
(not (empty? resolved-js-envs))
        at doo.core$assert_alias.invokeStatic(core.clj:61)
        at doo.core$assert_alias.invoke(core.clj:55)
        at leiningen.doo$doo.invokeStatic(doo.clj:214)
        at leiningen.doo$doo.doInvoke(doo.clj:193)
        at clojure.lang.RestFn.invoke(RestFn.java:460)
        at clojure.lang.Var.invoke(Var.java:394)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at leiningen.core.main$partial_task$fn__4667.doInvoke(main.clj:284)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at leiningen.core.main$apply_task.invokeStatic(main.clj:334)
        at leiningen.core.main$apply_task.invoke(main.clj:320)
        at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:340)
        at leiningen.core.main$resolve_and_apply.invoke(main.clj:336)
        at leiningen.core.main$_main$fn__4734.invoke(main.clj:420)
        at leiningen.core.main$_main.invokeStatic(main.clj:411)
        at leiningen.core.main$_main.doInvoke(main.clj:408)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at clojure.lang.Var.invoke(Var.java:394)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.main$main_opt.invokeStatic(main.clj:314)
        at clojure.main$main_opt.invoke(main.clj:310)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:512)
        at clojure.lang.Var.invoke(Var.java:409)
        at clojure.lang.AFn.applyToHelper(AFn.java:178)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
```

**Comment by miikka** [comment]
Now released in `[lein-doo "0.1.11"]`.
